<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Santhosh" name="Test" tests="4" failures="1" timestamp="20 Jun 2020 12:33:06 GMT" time="5.361" errors="0">
  <testcase name="SecondTest" time="3.809" classname="Soap.testRunner2"/>
  <testcase name="SingleTest" time="0.032" classname="Soap.testRunner2"/>
  <testcase name="SoapTest" time="1.308" classname="Rest.restRunner"/>
  <testcase name="SoapTest" time="0.201" classname="Soap.Soap">
    <failure type="java.lang.AssertionError" message="expected [FAILED] but found [FINISHED]">
      <![CDATA[java.lang.AssertionError: expected [FAILED] but found [FINISHED]
	at Soap.Soap.SoapTest(Soap.java:39)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SoapTest -->
</testsuite> <!-- Test -->
